import { Zone, Province, Branch, ColumnSetting } from '../types';

export const DEFAULT_ZONES: Zone[] = [
  { id: 'z1', name: 'Zona Norte', color: '#10b981' }, // Emerald
  { id: 'z2', name: 'Zona Sur-Este', color: '#3b82f6' }, // Blue
  { id: 'z3', name: 'Zona Sur-Oeste', color: '#f59e0b' }, // Amber
];

export const DEFAULT_PROVINCES: Province[] = [
  { id: 'p1', name: 'Santiago', zoneId: 'z1' },
  { id: 'p2', name: 'Espaillat', zoneId: 'z1' },
  { id: 'p3', name: 'Valverde', zoneId: 'z1' },
  { id: 'p4', name: 'Duarte', zoneId: 'z1' },
  { id: 'p5', name: 'La Vega', zoneId: 'z1' },
  { id: 'p6', name: 'Monseñor Nouel', zoneId: 'z1' },
  { id: 'p7', name: 'Maria Trinidad Sanchez', zoneId: 'z1' },
  { id: 'p8', name: 'Samana', zoneId: 'z1' },
  { id: 'p9', name: 'Santo Domingo', zoneId: 'z2' },
  { id: 'p10', name: 'Higüey', zoneId: 'z2' },
  { id: 'p11', name: 'San Cristobal', zoneId: 'z3' },
];

export const DEFAULT_BRANCHES: Branch[] = [
  {
    id: 'b1',
    branchId: '3',
    name: 'Centro Historico',
    provinceId: 'p1',
    server: 'ST-CEHIST-SV-PS',
    cc: '3',
    ip: '192.168.22.204',
    db: 'FEXPharmacySoftRDPtoVtaSuc3',
    backups: 'SI',
    externalDisk: 'SI',
    dataReduction: 'SI',
    emailValidation: 'SI',
    ftp: 'SI',
    s3: 'SI',
    voxelLog: 'SI',
    failOver: 'SI',
    voxel: 'SI',
    updateBox: 'SI',
    bkConsecutivo: 'NO',
    status: 'active',
    createdAt: '2025-01-15T10:00:00.000Z',
    custom: {}
  },
  {
    id: 'b2',
    branchId: '4',
    name: 'Cerros de Gurabo',
    provinceId: 'p1',
    server: 'ST-GURB-SV-PS',
    cc: '4',
    ip: '192.168.52.204',
    db: 'FEXPharmacySoftRDPtoVtaSuc04',
    backups: 'SI',
    externalDisk: 'SI',
    dataReduction: 'SI',
    emailValidation: 'SI',
    ftp: 'SI',
    s3: 'SI',
    voxelLog: 'SI',
    failOver: 'SI',
    voxel: 'SI',
    updateBox: 'SI',
    bkConsecutivo: 'NO',
    status: 'active',
    createdAt: '2025-01-18T10:00:00.000Z',
    custom: {}
  },
  {
    id: 'b3',
    branchId: '5',
    name: 'Villa Olimpica',
    provinceId: 'p1',
    server: 'ST-VO-SV-PS',
    cc: '5',
    ip: '192.168.54.204',
    db: 'FEXPharmacySoftRDPtoVtaSuc05',
    backups: 'SI',
    externalDisk: 'SI',
    dataReduction: 'SI',
    emailValidation: 'SI',
    ftp: 'SI',
    s3: 'SI',
    voxelLog: 'SI',
    failOver: 'SI',
    voxel: 'SI',
    updateBox: 'SI',
    bkConsecutivo: 'NO',
    status: 'active',
    createdAt: '2025-01-20T10:00:00.000Z',
    custom: {}
  },
  {
    id: 'b4',
    branchId: '6',
    name: 'Cristo Rey',
    provinceId: 'p1',
    server: 'ST-CR-SV-PS',
    cc: '6',
    ip: '192.168.50.204',
    db: 'FEXPharmacySoftRDPtoVtaSuc6',
    backups: 'SI',
    externalDisk: 'SI',
    dataReduction: 'SI',
    emailValidation: 'SI',
    ftp: 'SI',
    s3: 'SI',
    voxelLog: 'SI',
    failOver: 'SI',
    voxel: 'SI',
    updateBox: 'SI',
    bkConsecutivo: 'NO',
    status: 'active',
    createdAt: '2025-01-22T10:00:00.000Z',
    custom: {}
  },
  {
    id: 'b5',
    branchId: '7',
    name: 'Plaza Las Americas',
    provinceId: 'p1',
    server: 'ST-PLA-SV-PS',
    cc: '7',
    ip: '192.168.55.204',
    db: 'FEXPharmacySoftRDPtoVtaSuc7',
    backups: 'SI',
    externalDisk: 'SI',
    dataReduction: 'SI',
    emailValidation: 'SI',
    ftp: 'SI',
    s3: 'SI',
    voxelLog: 'SI',
    failOver: 'SI',
    voxel: 'SI',
    updateBox: 'SI',
    bkConsecutivo: 'NO',
    status: 'active',
    createdAt: '2025-01-25T10:00:00.000Z',
    custom: {}
  },
  {
    id: 'b6',
    branchId: '8',
    name: 'Moca Central',
    provinceId: 'p2',
    server: 'ST-MOC-SV-PS',
    cc: '8',
    ip: '192.168.60.204',
    db: 'FEXPharmacySoftRDPtoVtaSuc8',
    backups: 'SI',
    externalDisk: 'Solicitado',
    dataReduction: 'SI',
    emailValidation: 'SI',
    ftp: 'SI',
    s3: 'NO',
    voxelLog: 'SI',
    failOver: 'NO',
    voxel: 'SI',
    updateBox: 'SI',
    bkConsecutivo: 'NO',
    status: 'active',
    createdAt: '2025-02-01T10:00:00.000Z',
    custom: {}
  },
  {
    id: 'b7',
    branchId: '9',
    name: 'Metropolitana Santo Domingo',
    provinceId: 'p9',
    server: 'ST-SD-SV-PS',
    cc: '9',
    ip: '192.168.10.204',
    db: 'FEXPharmacySoftRDPtoVtaSuc9',
    backups: 'SI',
    externalDisk: 'SI',
    dataReduction: 'SI',
    emailValidation: 'SI',
    ftp: 'SI',
    s3: 'SI',
    voxelLog: 'SI',
    failOver: 'SI',
    voxel: 'SI',
    updateBox: 'SI',
    bkConsecutivo: 'SI',
    status: 'active',
    createdAt: '2025-02-05T10:00:00.000Z',
    custom: {}
  },
  {
    id: 'b8',
    branchId: '10',
    name: 'Higüey Bávaro',
    provinceId: 'p10',
    server: 'ST-HIG-SV-PS',
    cc: '10',
    ip: '192.168.15.204',
    db: 'FEXPharmacySoftRDPtoVtaSuc10',
    backups: 'Solicitado',
    externalDisk: 'NO',
    dataReduction: 'SI',
    emailValidation: 'NO',
    ftp: 'SI',
    s3: 'NO',
    voxelLog: 'NA',
    failOver: 'NO',
    voxel: 'SI',
    updateBox: 'SI',
    bkConsecutivo: 'NO',
    status: 'active',
    createdAt: '2025-02-10T10:00:00.000Z',
    custom: {}
  },
  {
    id: 'b9',
    branchId: '11',
    name: 'San Cristóbal Centro',
    provinceId: 'p11',
    server: 'ST-SC-SV-PS',
    cc: '11',
    ip: '192.168.18.204',
    db: 'FEXPharmacySoftRDPtoVtaSuc11',
    backups: 'SI',
    externalDisk: 'SI',
    dataReduction: 'SI',
    emailValidation: 'SI',
    ftp: 'SI',
    s3: 'SI',
    voxelLog: 'SI',
    failOver: 'SI',
    voxel: 'SI',
    updateBox: 'SI',
    bkConsecutivo: 'NO',
    status: 'closed',
    createdAt: '2025-02-12T10:00:00.000Z',
    custom: {}
  }
];

export const DEFAULT_COLUMN_DEFS: { key: string; label: string; locked?: boolean }[] = [
  { key: 'name', label: 'Sucursal', locked: true },
  { key: 'branchId', label: 'ID' },
  { key: 'province', label: 'Provincia' },
  { key: 'zone', label: 'Zona' },
  { key: 'server', label: 'Servidor' },
  { key: 'cc', label: 'CC' },
  { key: 'ip', label: 'IP' },
  { key: 'db', label: 'Base de Datos' },
  { key: 'backups', label: 'BackUps' },
  { key: 'externalDisk', label: 'Disco Ext.' },
  { key: 'dataReduction', label: 'Reducc. Datos' },
  { key: 'emailValidation', label: 'Valid. Correos' },
  { key: 'ftp', label: 'FTP' },
  { key: 's3', label: 'Subir S3' },
  { key: 'voxelLog', label: 'VoxelLog' },
  { key: 'failOver', label: 'FailOver' },
  { key: 'voxel', label: 'Voxel' },
  { key: 'updateBox', label: 'Act. Caja' },
  { key: 'bkConsecutivo', label: 'BK Consec.' },
  { key: 'createdAt', label: 'Fecha Reg.' },
  { key: 'status', label: 'Estado', locked: true }
];

export const SERVICE_KEYS = [
  'backups',
  'externalDisk',
  'dataReduction',
  'emailValidation',
  'ftp',
  's3',
  'voxelLog',
  'failOver',
  'voxel',
  'updateBox',
  'bkConsecutivo'
] as const;
